### PR TITLE
The Start of looking to host images

### PR DESCRIPTION
**Pull request by Wolfkid200444**
Current Idea

- Only Publish image once is verified (prevents spamming github api)
- Use Discord own Attachment option, to completely remove creation with url

### CODE REVIEW

**Comment by SomeAspy** [comment]
I'm not a fan of using github as a CDN

**Comment by Wolfkid200444** [comment]
what would u consider as a alternative?

**Comment by SomeAspy** [comment]
We would probably be cool just putting our own VPS behind cloudflare
I will have to look at this more.
We could also use an S3 bucket or similar

This looks cool. https://github.com/Pixboost/transformimgs

Again, I will have to look into this - not the biggest priority since the end of external access to the discord CDN is not too close

**Comment by Wolfkid200444** [comment]
We still got time on how we can come up with a solution so we will keep the pr open for suggestions and commits

**Comment by SomeAspy** [comment]
Will prep PR when ready

**Pull request closed without merging**
